Test 13

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,5 +35,10 @@ jobs:
         run: |-
           OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
           OIDC_JWT=$(echo $OIDC_TOKEN | jq -j '.value')
-          JWT=$(curl -sLS -X POST "https://fresh-turkey-76.loca.lt/api/auth/swap" -H "Authorization: GithubOIDC $OIDC_JWT")
-          echo $JWT
+          RESPONSE=$(curl -sLS -X POST "https://fresh-turkey-76.loca.lt/api/auth/swap" -H "Authorization: GithubOIDC $OIDC_JWT")
+          if [[ "$STR" == *"error"* ]]; then
+            echo "It's an error."
+            exit 1
+          then
+            echo $RESPONSE
+          fi
